# Generated by Django 3.0.6 on 2020-11-15 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Socialite', '0003_auto_20201113_0720'),
        ('PLACEUP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('INERNSHIP', 'INERNSHIP'), ('JOB', 'JOB')], max_length=20)),
                ('emp_type', models.CharField(choices=[('Part Time Job', 'Part Time Job'), ('Full Time Job', 'Full Time Job')], max_length=50)),
                ('work_name', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=250)),
                ('min_requirement', models.TextField(max_length=250)),
                ('location', models.CharField(max_length=100)),
                ('experience_or_time', models.CharField(max_length=10)),
                ('tech_stack', models.CharField(max_length=100)),
                ('posted', models.DateField(auto_now_add=True)),
                ('number_of_vacancy', models.CharField(max_length=3)),
                ('status', models.BooleanField(default=True)),
                ('salary_or_stipend', models.CharField(max_length=20)),
                ('applicants', models.ManyToManyField(to='Django_Socialite.Profile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PLACEUP.CompanyProfile')),
            ],
        ),
    ]
