# Generated by Django 3.0.6 on 2020-11-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLACEUP', '0003_auto_20201115_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='Type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='work',
            name='emp_type',
            field=models.CharField(max_length=50),
        ),
    ]
