# Generated by Django 3.0.6 on 2020-11-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Socialite', '0003_auto_20201113_0720'),
        ('PLACEUP', '0004_auto_20201115_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='resume_selected',
            field=models.ManyToManyField(related_name='resume_selected', to='Django_Socialite.Profile'),
        ),
    ]
