# Generated by Django 3.0.6 on 2020-11-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_Socialite', '0003_auto_20201113_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=models.CharField(max_length=210, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.CharField(max_length=210, null=True),
        ),
    ]
